const menu_data = [
  {
    id: 1,
    mega_menu: false,
    has_dropdown: true,
    title: "Why We?",
    link: "/",
    active: "active",
    sub_menus: [
      { link: "/about", title: "About framespik" },
      { link: "/contact", title: "Contact Us" },
      { link: "/faq", title: "FAQ" },
      { link: "/career", title: "Career" },
      { link: "/team", title: "Team Involved" },
      { link: "/learning-school", title: "Learning Videos" },
    ],
  },
  {
    id: 2,
    mega_menu: false,
    has_dropdown: true,
    title: "Features & Tools",
    link: "/features",
    active: "",
    sub_menus: [
      { link: "/photo-selection", title: "Photo Selection" },
      { link: "/data-safe", title: "100% Data Secure" },
      { link: "/storage", title: "Storage", badge: "1 Tb Free" },
      { link: "/custom-app", title: "Own Branding App" },
      { link: "/custom-website", title: "Own Branding Website" },
      { link: "/shared-cloud", title: "Shared Cloud Space" },
      { link: "/cloud-rentals", title: "Storage Rentals" },
      { link: "/vision-camera", title: "Vision Camera", badge: "Trending" },
      { link: "/data-backup", title: "15 Years Event Backup" },
      { link: "/ai-image-delivery", title: "Unlimited Ai Share" },
      { link: "/unlimited-album-videos", title: "4K Videos & Images" },
      { link: "/3d-album", title: "Unlimited 3D Albums" },
      {
        link: "/3rd-party-integration",
        title: "3rd Party Integration",
        badge: "New",
      },
    ],
  },
  {
    id: 3,
    mega_menu: false,
    has_dropdown: true,
    title: "CRM",
    link: "/crm-tools",
    active: "",
    sub_menus: [
      { link: "/work-updates", title: "Work Updates" },
      { link: "/payment-remainders", title: "Payment Remainders" },
      { link: "/any-where-view", title: "Any Where View" },
      { link: "/nfc-cards", title: "NFC cards" },
      { link: "/scheduling", title: "Scheduling" },
      { link: "/memory-page", title: "Memory Page" },
      {
        link: "/track-and-analyze-finance",
        title: "Finance Tracking",
        badge: "Realtime",
      },
    ],
  },
  {
    id: 4,
    mega_menu: false,
    has_dropdown: true,
    title: "Pricing",
    link: "/pricing",
    active: "",
    sub_menus: [
      {
        link: "/plans-pricing",
        title: "Plans & Pricing",
        badge: "Starts 8K/Yr",
      },
      { link: "/update-charges", title: "Updates Charges" },
      { link: "/other-charges", title: "Other Charges" },
    ],
  },
  {
    id: 5,
    mega_menu: false,
    has_dropdown: false,
    title: "Blogs",
    link: "/blogs",
    active: "",
    sub_menus: [{ link: "/blog-view", title: "Blog-view" }],
  },
];
export default menu_data;
